server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smartplan
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  show-actuator: true

management:
  server:
    port: 8180
  endpoint:
    loggers:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        web: INFO

jwt:
  access-token:
    lifeTime: 5
  refresh-token:
    lifeTime: 10
  secret-key: TXlTdXBlckhlbGxvV29ybGRKd3RTaWduS2V5QW5kT0F1dGg=


